language: python
branches:
  only:
  - source
install:
- pip install -r requirements.txt
before_install:
- openssl aes-256-cbc -K $encrypted_713170cfc4d9_key -iv $encrypted_713170cfc4d9_iv
  -in deploy_key.enc -out deploy_key -d
- chmod 600 deploy_key
- mv deploy_key ~/.ssh/id_rsa
- git remote add deploy ssh://git@github.com/${TRAVIS_REPO_SLUG}.git
script:
- make publish github
